// Code generated by goctl. DO NOT EDIT.
package types

type TranslateReq struct {
	Name   string `path:"name"`
	From   string `json:"from,options=zh|uk"`
	Target string `json:"target,options=zh|uk"`
}

type TranslateResp struct {
	Result string `json:"result"`
}
