// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	translate "github.com/yguilai/pipiao-openapi/app/openpapi/internal/handler/translate"
	"github.com/yguilai/pipiao-openapi/app/openpapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Oauth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/translate/zh/:name",
					Handler: translate.TranslateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/wf/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/trigger",
				Handler: translate.TriggerHandler(serverCtx),
			},
		},
		rest.WithPrefix("/wf/v1"),
	)
}
